### ISSUE TITLE
 README.md installation instructions

### ISSUE THREAD

**Issue by dkosovic** [katalix/go-l2tp#3]
The  README.md installation instructions say to do `go get github.com/katalix/go-l2tp`, but that results in the following error:

```
$ go get github.com/katalix/go-l2tp
package github.com/katalix/go-l2tp: no Go files in /home/foo/go/src/github.com/katalix/go-l2tp
```
I believe the instructions should actually be `go get github.com/katalix/go-l2tp/...`

**Comment by dkosovic** [comment]
With Go >= 1.17 it should be :
```
go install "github.com/katalix/go-l2tp/...@latest"
```

As the following now happens with `go get` :
```
$ go get github.com/katalix/go-l2tp/...
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Comment by tomparkin** [comment]
Thanks @dkosovic and I'm sorry I missed this issue!  For whatever reason my github notifications were not working :-|

I will look into updating the documentation as suggested.
